version: "3"
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    #network_mode: "host"
    ports:
      - "16686:16686"
      - "14250"

  #Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    #network_mode: "host"
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    #network_mode: "host"
    ports:
      # - "1888:1888"   # pprof extension
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      # - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      # - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin

  # # Expose the frontend on http://localhost:8081
  # frontend:
  #   image: openzipkin/example-sleuth-webmvc
  #   command: Frontend
  #   environment:
  #     JAVA_OPTS: -Dspring.zipkin.baseUrl=http://otel-collector:9411
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - otel-collector

  # # Expose the backend on http://localhost:9000
  # backend:
  #   image: openzipkin/example-sleuth-webmvc
  #   command: Backend
  #   environment:
  #     JAVA_OPTS: -Dspring.zipkin.baseUrl=http://otel-collector:9411
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - otel-collector
